"""initial schema

Revision ID: 75b026787526
Revises: 
Create Date: 2026-08-20 22:54:16.808353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.types


# revision identifiers, used by Alembic.
revision: str = '75b026787526'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deals',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('workspace_id', app.types.GUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('investment_type', sa.String(length=50), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('subsector', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('unit_scale', sa.String(length=20), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=True),
    sa.Column('fiscal_year_end', sa.String(length=5), nullable=True),
    sa.Column('forecast_years', sa.Integer(), nullable=False),
    sa.Column('investment_thesis', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', app.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_memberships',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('workspace_id', app.types.GUID(), nullable=False),
    sa.Column('user_id', app.types.GUID(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', 'viewer', name='workspace_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_workspace_user')
    )
    op.create_table('assumption_sets',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('deal_id', app.types.GUID(), nullable=False),
    sa.Column('scenario', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('wacc', sa.Float(), nullable=False),
    sa.Column('terminal_growth_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id', 'scenario', name='uq_deal_scenario')
    )
    op.create_table('audit_logs',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('workspace_id', app.types.GUID(), nullable=True),
    sa.Column('deal_id', app.types.GUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value_json', sa.JSON(), nullable=True),
    sa.Column('new_value_json', sa.JSON(), nullable=True),
    sa.Column('actor_id', app.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_periods',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('deal_id', app.types.GUID(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('is_historical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id', 'fiscal_year', 'period_type', name='uq_deal_fy_type')
    )
    op.create_table('model_versions',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('deal_id', app.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scenario_default', sa.String(length=20), nullable=False),
    sa.Column('input_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('calculation_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('created_by', app.types.GUID(), nullable=True),
    sa.Column('approved_by', app.types.GUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_documents',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('deal_id', app.types.GUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=200), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('uploaded_by', app.types.GUID(), nullable=True),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assumptions',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('assumption_set_id', app.types.GUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=30), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assumption_set_id'], ['assumption_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assumption_set_id', 'key', 'fiscal_year', name='uq_assumption_set_key_year')
    )
    op.create_table('export_jobs',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('model_version_id', app.types.GUID(), nullable=False),
    sa.Column('export_type', sa.String(length=10), nullable=False),
    sa.Column('scenario', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_line_items',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('deal_id', app.types.GUID(), nullable=False),
    sa.Column('period_id', app.types.GUID(), nullable=False),
    sa.Column('statement_type', sa.String(length=30), nullable=False),
    sa.Column('reported_label', sa.String(length=255), nullable=False),
    sa.Column('normalized_key', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit_scale', sa.String(length=20), nullable=False),
    sa.Column('source_document_id', app.types.GUID(), nullable=True),
    sa.Column('mapping_status', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['financial_periods.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valuation_runs',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('model_version_id', app.types.GUID(), nullable=False),
    sa.Column('scenario', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('inputs_json', sa.JSON(), nullable=False),
    sa.Column('outputs_json', sa.JSON(), nullable=False),
    sa.Column('model_check_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valuation_runs')
    op.drop_table('financial_line_items')
    op.drop_table('export_jobs')
    op.drop_table('assumptions')
    op.drop_table('source_documents')
    op.drop_table('model_versions')
    op.drop_table('financial_periods')
    op.drop_table('audit_logs')
    op.drop_table('assumption_sets')
    op.drop_table('workspace_memberships')
    op.drop_table('deals')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
